Project 2 Dimension Data Collab/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Test_Database.Models;
using Microsoft.AspNetCore.Authorization;

namespace Test_Database.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {

        private readonly RoleManager<IdentityRole> roleManager;


        public  AdministrationController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRole model)
        {
            if(ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole
                {
                    Name = model.RoleName
                
                };

                IdentityResult res = await roleManager.CreateAsync(role);

                if (res.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }

                foreach(IdentityError err in res.Errors)
                {
                    ModelState.AddModelError("", err.Description);

                }
            }

            return View(model);
        }
    }
}

Project 2 Dimension Data Collab/Controllers/Cmpg323Project2DatasetController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Test_Database.Data;
using Test_Database.Models;


namespace Test_Database.Controllers
{
    [Authorize]
    public class Cmpg323Project2DatasetController : Controller

        
    {
        private readonly Project2Context _context;

        public Cmpg323Project2DatasetController(Project2Context context)
        {
            _context = context;
        }

        // GET: Cmpg323Project2Dataset

        [Route("data/index")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cmpg323Project2Dataset.ToListAsync());
        }

        // GET: Cmpg323Project2Dataset/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cmpg323Project2Dataset = await _context.Cmpg323Project2Dataset
                .FirstOrDefaultAsync(m => m.EmployeeNumber == id);
            if (cmpg323Project2Dataset == null)
            {
                return NotFound();
            }

            return View(cmpg323Project2Dataset);
        }



        // GET: Cmpg323Project2Dataset/Create

        //[Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cmpg323Project2Dataset/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager")] Cmpg323Project2Dataset cmpg323Project2Dataset)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cmpg323Project2Dataset);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cmpg323Project2Dataset);
        }

        // GET: Cmpg323Project2Dataset/Edit/5

        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cmpg323Project2Dataset = await _context.Cmpg323Project2Dataset.FindAsync(id);
            if (cmpg323Project2Dataset == null)
            {
                return NotFound();

            }

            var personID = (_context.AspNetUsers.Where(x => x.Email == User.Identity.Name).Select(x => x.Id));
            var person = personID.ToList()[0];
            var ISAdmin = _context.AspNetUserRoles.Where(x => x.UserId == person).Select(x => x.RoleId);
            ViewBag.Admin = JsonConvert.SerializeObject(ISAdmin);

            return View(cmpg323Project2Dataset);
        }

        // POST: Cmpg323Project2Dataset/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id, [Bind("Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager")] Cmpg323Project2Dataset cmpg323Project2Dataset)
        {
            if (id != cmpg323Project2Dataset.EmployeeNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cmpg323Project2Dataset);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Cmpg323Project2DatasetExists(cmpg323Project2Dataset.EmployeeNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cmpg323Project2Dataset);
        }

        // GET: Cmpg323Project2Dataset/Delete/5

        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cmpg323Project2Dataset = await _context.Cmpg323Project2Dataset
                .FirstOrDefaultAsync(m => m.EmployeeNumber == id);
            if (cmpg323Project2Dataset == null)
            {
                return NotFound();
            }

            return View(cmpg323Project2Dataset);
        }

        // POST: Cmpg323Project2Dataset/Delete/5

        //[Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cmpg323Project2Dataset = await _context.Cmpg323Project2Dataset.FindAsync(id);
            _context.Cmpg323Project2Dataset.Remove(cmpg323Project2Dataset);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Cmpg323Project2DatasetExists(string id)
        {
            return _context.Cmpg323Project2Dataset.Any(e => e.EmployeeNumber == id);
        }
    }
}

Project 2 Dimension Data Collab/Controllers/dataChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Test_Database.Data;

namespace Test_Database.Controllers
{
    [Authorize]
    public class dataChartController : Controller
    {

        private readonly Project2Context _context;

        public dataChartController(Project2Context context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Dashboard()
        {
            #region Chart 1
                var x = _context.Cmpg323Project2Dataset.Where(x => x.Gender == "Male").Count();
                var y = _context.Cmpg323Project2Dataset.Where(y => y.Gender == "Female").Count();
            

                ViewBag.male = JsonConvert.SerializeObject(x);
                ViewBag.female = JsonConvert.SerializeObject(y);
            #endregion



            #region Chart 2
                var healthRep = _context.Cmpg323Project2Dataset.Where(healthRep => healthRep.JobRole == "Healthcare Representative").Count();
                var humanRe = _context.Cmpg323Project2Dataset.Where(humanRe => humanRe.JobRole == "Human Resources").Count();
                var labTech = _context.Cmpg323Project2Dataset.Where(labTech => labTech.JobRole == "Laboratory Technician").Count();
                var manag = _context.Cmpg323Project2Dataset.Where(manag => manag.JobRole == "Manager").Count();
                var manuDir = _context.Cmpg323Project2Dataset.Where(manuDir => manuDir.JobRole == "Manufacturing Director").Count();
                var resDir = _context.Cmpg323Project2Dataset.Where(resDir => resDir.JobRole == "Research Director").Count();
                var resSci = _context.Cmpg323Project2Dataset.Where(resSci => resSci.JobRole == "Research Scientist").Count();
                var salesEx = _context.Cmpg323Project2Dataset.Where(salesEx => salesEx.JobRole == "Sales Executive").Count();
                var salesRep = _context.Cmpg323Project2Dataset.Where(salesRep => salesRep.JobRole == "Sales Representative").Count();

                ViewBag.HealthRep = JsonConvert.SerializeObject(healthRep);
                ViewBag.HumanR = JsonConvert.SerializeObject(humanRe);
                ViewBag.LabTech = JsonConvert.SerializeObject(labTech);
                ViewBag.Mana = JsonConvert.SerializeObject(manag);
                ViewBag.ManuDir = JsonConvert.SerializeObject(manuDir);
                ViewBag.ResDir = JsonConvert.SerializeObject(resDir);
                ViewBag.ResSci = JsonConvert.SerializeObject(resSci);
                ViewBag.SalesEx = JsonConvert.SerializeObject(salesEx);
                ViewBag.SalesRep = JsonConvert.SerializeObject(salesRep);

            #endregion

            #region Chart 3
                var HumanR = _context.Cmpg323Project2Dataset.Where(HumanR => HumanR.Department == "Human Resources").Count();
                var resDev= _context.Cmpg323Project2Dataset.Where(resDev => resDev.Department == "Research & Development").Count();
                var sales = _context.Cmpg323Project2Dataset.Where(sales => sales.Department == "Sales").Count();


                ViewBag.HumanRe = JsonConvert.SerializeObject(HumanR);
                ViewBag.ResDev = JsonConvert.SerializeObject(resDev);
                ViewBag.Sales = JsonConvert.SerializeObject(sales);

            #endregion

            return View();

        }

    }
}

Project 2 Dimension Data Collab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Home-Dimension Data Collab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/dist/Chart.js"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dimension Data Collab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cmpg323Project2Dataset" asp-action="Index">View Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="dataChart" asp-action="Dashboard">Data Analytics</a>
                        </li>
                        @* Navigate to the Role view
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="Create">Role management</a>
                        </li>
                        *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary">
        <div class="container">
            &copy; 2020 - Dimension Data Collab - <a asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>